# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift Dev Sandbox'
    version: '4.6'
    proxy: 'https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift Dev Sandbox'
    version: '4.6'
    cmd: 'oc start-build dotnet-ex --follow'
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Openshift Dev Sandbox'
    version: '4.6'
    cmd: 'oc status'